### ISSUE TITLE
Nuxt is removing universal selectors from css

### ISSUE THREAD

**Issue by danchristofi** [nuxt/nuxt.js#10165]
### Versions

- nuxt: ^2.15.7
- node: v15.10.0

### Steps to reproduce

Inside my index.vue page I have the following in the styling:

``` scss
<style lang="scss">
    *:where(:not(iframe, canvas, img, svg, video):not(svg *, symbol *)) {
      all: unset;
      display: revert;
    }
    
    *,
    *::before,
    *::after {
      box-sizing: border-box;
    }
</style>
```

Locally this works fine, but doesn't work after deploying on vercel. When inspecting the source on this version I can see that the * selectors have been removed:

`:where(:not(iframe):not(canvas):not(img):not(svg):not(video):not(svg*):not(symbol*)){all:unset;display:revert}*,:after,:before{box-sizing:border-box}`

The same thing happens regardless of how it's imported, whether by importing a separate file in the config, or importing a file inside the style tags. 

If I create a custom app.html and add the css manually in the HEAD, the * still gets removed, but this way makes the issue happen locally as well.
