### ISSUE TITLE
Transitions works only on some pages

### ISSUE THREAD

**Issue by Kcko** [nuxt/nuxt.js#10226]
Hi,

im learning nuxt and i see some strange behavior with transitions.

I created css file with page transition (from manual).
Test app has 2 layouts (for learning / testing), 2 simple pages and 1 dynamic page.

Transition works only for dynamic page. How it is possible? Im begginer with NUXT so I apologize in advance if I missed anything.

Thx for help.

Test project: https://kcko.netlify.app/
Github: https://github.com/Kcko/nuxt-sandbox

**Comment by NicolasV** [comment]
Hi @Kcko,

I think this happens because you switch layouts between your index and custom pages.

To apply a transition to the change of layout, you must add this to your css file (`layout` being the default):

```css
.layout-enter-active,
.layout-leave-active {
  transition: opacity 0.3s;
}
.layout-enter,
.layout-leave-active {
  opacity: 0;
}
```

Hope that helps !
