### ISSUE TITLE
how to run Nuxt in production

### ISSUE THREAD

**Issue by raisiqueira** [nuxt/nuxt.js#1038]
Hey! i'm question, how to deploy Nuxtjs on production with Docker.

**Comment by pi0** [comment]
Hey. We have not an official guide for docker (yet). But this [Dockerfile](https://github.com/nuxt/hackernews/blob/master/Dockerfile) would be a good reference to get idea how to do that.

**Comment by raisiqueira** [comment]
@pi0 I circled your Dockerfile, but it did not work.

**Comment by pi0** [comment]
So would you please share more about errors? What's failing?

**Comment by raisiqueira** [comment]
I'm running exactly your Dockerfile, however when I access the HOST: DOOR the request is not complete. The container is running normal, but does not access via HOST: PORT

**Comment by raisiqueira** [comment]
On play-with-docker.com show the `Error forwarding request.`.

**Comment by pi0** [comment]
The instance should be reachable with internal port 3000 (as is preconfigured in mentioned Dockerfile). So:

```bash
# run in project root with Dockerfile
docker build -t nuxt-example .

# Run instance in foreground
docker run -it --rm -p 8080:3000 nuxt-example
```

I'll try to provide more detailed examples later.

**Comment by pi0** [comment]
Also about play-with-docker not personally tried it. Maybe @Tabrizian should give us some help :)

**Comment by Tabrizian** [comment]
I think the problem in here is that there is a missing ```ENV HOST 0.0.0.0``` in the ```Dockerfile``` and also there is a middleware redirecting http requests to https. If you add ```ENV HOST 0.0.0.0``` in the Dockerfile of your project root I think your problem should be solved.

**Comment by raisiqueira** [comment]
@Tabrizian this is my Dockerfile:
```
FROM node:8-alpine

MAINTAINER Rai Siqueira

ENV HOST 0.0.0.0

RUN echo "--->>> creating app folder" && \
    mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY package.json /usr/src/app

RUN echo "--->>> Installing packages" && \
    npm install

COPY . /usr/src/app

EXPOSE 3000

CMD ["npm", "start"]
```

**Comment by raisiqueira** [comment]
That's my docker-compose.yml, and this work :rofl: 
```yml
version: "3"
services:
  front:
    image: node:7-slim
    working_dir: "/var/www/app"
    environment:
      - HOST=0.0.0.0
    ports:
      - "80:3000"
    volumes:
      - ./app:/var/www/app
    command: bash -c "npm install && npm run dev"
```
