### ISSUE TITLE
Custom App.html contents ignored when generating static site with GitHub action

### ISSUE THREAD

**Issue by katerlouis** [nuxt/nuxt.js#10792]
### Versions

- nuxt: 2.15.4
- node: 16.0

I need Google Tag Manager, Hotjar and a cookie consent solution in my HTML frame. I put the tags in `/App.html`. 

When I do `$ npm generate` locally, the tags end up in the generated files. But when I do it using GitHub actions, the scripts don't show up as if the file didn't exist.

Here's my yaml for the github action:

```yaml
name: Build to Staging

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Create .env file
      run: |
        touch .env
        echo STORYBLOK_PERSONAL_ACCESS_TOKEN=${{ secrets.STORYBLOK_PERSONAL_ACCESS_TOKEN }} >> .env
        echo STORYBLOK_PREVIEW_TOKEN=${{ secrets.STORYBLOK_PREVIEW_TOKEN }} >> .env
        echo CONVERTKIT_API_KEY=${{ secrets.CONVERTKIT_API_KEY }} >> .env
        echo STRIPE_CHECKOUT_HOST=${{ secrets.STRIPE_CHECKOUT_HOST }} >> .env
    - name: Install npm 8
      run: npm i -g npm@8 --registry=https://registry.npmjs.org
    - run: npm ci --legacy-peer-deps
    - run: npm run generate --if-present
    - name: Deploy to Staging server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        ARGS: "-avzr --delete"
        SOURCE: "dist/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }}
```

I double checked: The `App.html` does contain the desired contents on github. 

It seems that the remote `generate` process is using `.nuxt/views/app.template.html` instead of my custom one?

But why?
Any ideas? :(
