### ISSUE TITLE
route transition stops working when switching layout

### ISSUE THREAD

**Issue by uptownhr** [nuxt/nuxt.js#108]
If you have multiple layouts for different routes, moving to a route with a different layout causes the route transition to stop working.

**Comment by Atinux** [comment]
Hi @uptownhr 

Actually it's normal since the layout is different and the `<nuxt></nuxt>` component changed.

But you can handle layout transition for this case and disable the route transition to make the transition.

`layouts/default.vue`:
```html
<template>
  <transition name="layout" mode="out-in">
    <nuxt/>
  </transition>
</template>
```

`layouts/dark.vue`:
```html
<template>
  <transition name="layout" mode="out-in">
    <div class="dark">
      <nuxt/>
    </div>
  </transition>
</template>
```

Then,  you need to have a global css file in `assets/main.css`:
```css
.layout-enter-active, .layout-leave-to {
  transition: opacity .5s;
}
.layout-enter, .layout-leave-to {
  opacity: 0;
}
``` 

Make sure to set the CSS as global in `nuxt.config.js`:
```js
module.exports = {
  css: ['~assets/main.css']
}
```

Result:

![layout-transitions](http://i.imgur.com/FzF7sPc.gif)
