### ISSUE TITLE
Nuxt development server continiously restarts with `--https`

### ISSUE THREAD

**Issue by nandi95** [nuxt/nuxt.js#12748]

**Comment by rrolla** [comment]
Looks like that from version `3.7.1` to `3.7.2` websocket config is changed to hmr (hot module replacement) https://github.com/nuxt/nuxt/compare/v3.7.1...v3.7.2

previously it was connecting to

```
wss://docker.dev.gradio.lv/_nuxt/hmr/
```
because we setted in nuxt.config.ts vite.server.hmr.path


starting from version `3.7.2` looks like path not work anymore so it connects to
```
wss://docker.dev.gradio.lv/_nuxt/
```


To get it work with traefik loadbalancer i can completely remove two parts from previous config https://github.com/nuxt/nuxt/issues/12748#issuecomment-1397234718:


`nuxt.config.ts`

remove vite.server eg

```ts
  vite: {
    define: { 'process.env.DEBUG': false },
    },
  },
```

`docker-compose.yml`

remove vitesocket stuff

```yml
  gradiohead:
    container_name: gradio_head
    hostname: v5.docker.dev.gradio.lv
    image: node:14-alpine
    labels:
      - traefik.enable=true
      - traefik.http.routers.gradiohead_http.service=gradiohead
      - traefik.http.routers.gradiohead_http.rule=Host(`docker.dev.gradio.lv`, `v5.docker.dev.gradio.lv`)
      - traefik.http.routers.gradiohead_http.entrypoints=http
      - traefik.http.routers.gradiohead_http.middlewares=redirect-to-https

      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.gradiohead.service=gradiohead
      - traefik.http.services.gradiohead.loadbalancer.server.port=3000
      - traefik.http.routers.gradiohead.rule=Host(`docker.dev.gradio.lv`, `v5.docker.dev.gradio.lv`)
      - traefik.http.routers.gradiohead.entrypoints=https
      - traefik.http.routers.gradiohead.tls=true

    expose:
      - 3000
    command: >
        /bin/sh -c "yarn && yarn dev"
```

**Comment by Drew-Macgibbon** [comment]
Using `Nuxt 3.10.3` with `Docker` on `Windows`.
`HMR` wasn't working for me out of the box (multiple projects with different versions of Nuxt).

For me the solution was to add this:

**nuxt.config.ts**

```ts
 $development: {
    vite: {
      server: {
        watch: {
          usePolling: true,
          interval: 1000, // set preference
        },
      },
    },
  },
```

**Dockerfile**
```dockerfile
EXPOSE 3000 24678
CMD rm -rf /tmp/nitro && npm run dev
```

**docker-compose.yml**

```yml
 ports:
      - 3000:3000
      - 24678:24678
  environment:
      - HOST=0.0.0.0
 ```
