### ISSUE TITLE
error on import scss files !

### ISSUE THREAD

**Issue by miladmeidanshahi** [nuxt/nuxt.js#1424]
Hi,
I want to load uikit framework on my project but i got this error

`DocumentationGitHub
ERROR in ./node_modules/css-loader?sourceMap!./node_modules/uikit/dist/scss/uikit.scss
Module build failed: Unknown word (1:1)`
> 1 | // LESS related
    | ^
  2 | @import "core/variables.scss";
  3 | 
  4 | // Defaults

` @ ./node_modules/css-loader?sourceMap!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-0c4d0db8","scoped":false,"hasInlineConfig":true}!./node_modules/sass-loader/lib/loader.js?sourceMap!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./layouts/default.vue 5:10-95
 @ ./node_modules/vue-style-loader?sourceMap!./node_modules/css-loader?sourceMap!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-0c4d0db8","scoped":false,"hasInlineConfig":true}!./node_modules/sass-loader/lib/loader.js?sourceMap!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./layouts/default.vue
 @ ./layouts/default.vue
 @ ./node_modules/babel-loader/lib?{"presets":["stage-0"],"babelrc":false,"cacheDirectory":true}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./.nuxt/App.vue
 @ ./.nuxt/App.vue
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?name=$client&reload=true ./.nuxt/client.js`

**# when i remove `//` signes it pass but it shouldn't be like this.**

**Comment by cretueusebiu** [comment]
In `nuxt.config.js`, add the CSS resources:

```javascript
css: [
  '~/assets/main.scss'
]
```

Then in `assets/main.scss` import UIkit:

```scss
// https://getuikit.com/docs/sass#how-to-build

// 1. Your custom variables and variable overwrites.
$global-link-color: #DA7D02;

// 2. Import default variables and available mixins.
@import "~uikit/src/scss/variables-theme";
@import "~uikit/src/scss/mixins-theme";

// 3. Your custom mixin overwrites.
@mixin hook-card() { color: #000; }

// 4. Import UIkit.
@import "~uikit/src/scss/uikit-theme";
```
