### ISSUE TITLE
Chrome bug?  nuxt bug?

### ISSUE THREAD

**Issue by yoyo837** [nuxt/nuxt.js#1570]
OS: Win 10 latest;
Chrome: 60.0.3112.113 64bit;
template: nuxt/koa;

Sorry, My English...
When the transparency is switched, the page flashes unexpectedly.（At this time range -> transition: opacity 0.5s）

I'll upload screenshots later.

If I delete the code:
```css
.page-enter-active,
.page-leave-active {
    transition: opacity 0.5s
}

.page-enter,
.page-leave-active {
    opacity: 0
}
```
Cannot be reproduced that.
