### ISSUE TITLE
Input type being stripped on `nuxt generate`

### ISSUE THREAD

**Issue by stursby** [nuxt/nuxt.js#1760]
After running `nuxt generate` an `<input type="text" id="name">` becomes `<input id="name">`.

I made a demo repo here --> https://github.com/stursby/nuxt-tags-bug

For example, if I'm styling using the following, it's no longer applied after generating.

```css
input[type=text] {
  background: lightgray;
  outline: none;
  border: none;
}
```

Here's what it looks like when running `nuxt`

![image](https://user-images.githubusercontent.com/527849/31027458-df04ca4a-a50f-11e7-82bd-a9f3637c6965.png)

And then after running `nuxt generate`

![image](https://user-images.githubusercontent.com/527849/31027481-ef898536-a50f-11e7-8679-f9c869d95e46.png)
