### ISSUE TITLE
Not able to access ':root' pseudo class.

### ISSUE THREAD

**Issue by KyleTryon** [nuxt/nuxt.js#2067]
Attempting to use native CSS variables, I am not able to place the variables inside of the ':root' selector, the CSS is not compiled. When I move the variables into the 'body' selector they do work again. I am loading the css file via nuxt.config.js

**Comment by clarkdo** [comment]
I have tried as you description, it works for me, if I missed anything, you'd better create a repo can reproduce your problem.

```
// nuxt.config.js
module.exports = {
  css: ['~/assets/main.css']
}
```

```css
:root {
  --main-bg-color: brown;
}
body {
  background-color: var(--main-bg-color);
}
```
![image](https://user-images.githubusercontent.com/4312154/32643226-8fe41618-c59f-11e7-9fde-3a90c6e8570b.png)
