### ISSUE TITLE
Run nuxt start by pm2 start -i max npm -- start have error

### ISSUE THREAD

**Issue by yyyuuu777** [nuxt/nuxt.js#2630]
env: 

Using nginx as a reverse proxy
Nuxt  ^1.0.0-rc9

start 
```
 pm2 start -i max npm -- start
```

when i start by pm2, i get error :

![tt](https://user-images.githubusercontent.com/20697976/35105431-3ac6ccd0-fc9e-11e7-82be-3425cc3c5e77.png)

![screen shot 2561-01-18 at 22 32 51](https://user-images.githubusercontent.com/20697976/35105959-8f1ba854-fc9f-11e7-8e93-5287ab675e91.png)

I use ab test website 
```
ab -n 5000 -c 10 http://**/
```

when completed 1500 requests, process  will  block, as below 

![error3](https://user-images.githubusercontent.com/20697976/35104809-8c9e7c4e-fc9c-11e7-8e60-a84b88f435d3.jpg)

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2288">#c2288</a>)</em></sub></div>

**Comment by Cogitoergo** [comment]
First check if You have node or nodejs installed, then check if You have nuxt installed at all. Seems, like You dont or path of nuxt's bin can't be found. I'm 99% sure this is not the correct way to start up nuxt.js with PM2. :)

**Comment by Drezdenozk** [comment]
1. are you install node_modules after deploy OR you run "build" on the server?
2. try run 
pm2 start npm --name yourAppName -- run start

**Comment by trylovetom** [comment]
same here

**Comment by axetroy** [comment]
I got the same problems with Docker.

There is the ``docker-compose.yml``

```yml
version: "3"
services:
  web:
    build:
      context: .
      dockerfile: ./docker/web.Dockerfile
    user: "node"
    working_dir: /home/node/app
    environment:
      # - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
    volumes:
      - ./api:/home/node/app/api
      - ./dist:/home/node/app/dist
      - ./logs:/home/node/app/logs
      - ./pm2.json:/home/node/app/pm2.json
      - ./nuxt.config.js:/home/node/app/nuxt.config.js
      - ./app.config.js:/home/node/app/app.config.js
    command: ["pm2-runtime", "start", "pm2.json"]
    # command: ["pm2-runtime", "start" ,"npm", "--", "start"]
    # command: ["npm", "start"]
    ports:
      - 4000:3000
```

and here is the ``pm2.json``

```json
{
  "apps": [
    {
      "name": "admin",
      "instances": "1",
      "exec_mode": "cluster",
      "script": "npm",
      "args": "start",
      "cwd": "./"
    }
  ]
}
```

and ``npm start`` === ``nuxt start``

and got the same error.

### How I resolve it?

I change the ``npm start`` script with ``nuxt start .``

Why?

because the actually run command is

``nuxt start .`` >>  ``nuxt start . "pm2.json" "start"``

``nuxt start`` >>  ``nuxt start "pm2.json" "start"``

see that ? ``"pm2.json"`` folder doesn't exist at all.
