### ISSUE TITLE
loadingIndicator style on IE11

### ISSUE THREAD

**Issue by rktyt** [nuxt/nuxt.js#3214]
### Version

[v1.4.0](https://github.com/nuxt/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[https://codepen.io/rktyt/pen/jzJyem](https://codepen.io/rktyt/pen/jzJyem)

### Steps to reproduce

Please look on IE11.

### What is expected ?

The loading indicator shuld be center.

### What is actually happening?

The loading indicator was not center.

### Additional comments?

https://github.com/nuxt/nuxt.js/tree/v1.4.0/lib/app/views/loading

Solved style:

```css
body, html, #__nuxt {
  background-color: <%= options.background %>;
  width: 100%;
  height: 100%;
  display: flex;
  align-items: center;
  margin: 0;
  padding: 0;
}
```

or 

```css
body, html, #__nuxt {
  background-color: <%= options.background %>;
  width: 100%;
  height: 100%;
  display: flex;
  justify-content: center;
  flex-direction: column;
  align-items: center;
  margin: 0;
  padding: 0;
}
```

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c6882">#c6882</a>)</em></sub></div>
