### ISSUE TITLE
Consider removing CSSNext as a default

### ISSUE THREAD

**Issue by mirisuzanne** [nuxt/nuxt.js#3473]
Hi all, I've been enjoying what I can do Nuxt, but I was surprised when my CSS wasn't working the way I wrote it:

```scss
// input
.test { 
  background-image: var(--img, initial); 
} 

// output
.test { 
  background-image: none; 
  background-image: initial; 
}
```

That output does not in any way reflect the intent of my input.

This seems to be CSSNext's attempt at resolving CSS variables, but it's a dangerous approach that completely erases the power CSS variables provide. This is not at all how CSS variables are meant to be used, or meant to work. They cannot be accurately pre-processed, because their meaning (and power) relies on the DOM structure. This is one of the most powerful features available in CSS, and Nuxt now breaks it by default.

Please consider replacing CSSNext with Autoprefixer. It does everything you need for basic browser support, without breaking the core features of CSS. I shouldn't have to go digging around in the Nuxt config just to get my plain CSS working the way it was written.
