### ISSUE TITLE
CSS native variablles can't be modified inside media queries

### ISSUE THREAD

**Issue by sdq-sts** [nuxt/nuxt.js#3593]
### Version

[v1.0.0](https://github.com/nuxt.js/releases/tag/v1.0.0)

### Reproduction link

[https://github.com/sdq-sts/nuxt-css-native-variables](https://github.com/sdq-sts/nuxt-css-native-variables)

### Steps to reproduce

Download the repo, install the dependencies and run in dev mode.

### What is expected ?

Is expected the background  color change from `181818` to `fff` when the viewport is less than 960px just like the example bellow:

https://codepen.io/sadraque/pen/ejEBQo

### What is actually happening?

The variables doesn't change the background color when the viewport is less than 960px.

### Additional comments?

I'm using the following aditional packages:

```
  "nuxt-sass-resources-loader": "^2.0.3"
  "node-sass": "^4.9.2",
  "sass-loader": "^7.0.3"
```

Although I don't know if this is a issue with  `node-sass`, `sass-loader` or `nuxt-sass-resources-loader`,  `webpack` or even the `nuxt` itself.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7441">#c7441</a>)</em></sub></div>

**Comment by sdq-sts** [comment]
Just a update, I was able to make it work adding the default variables inside another media query.

```css
@media screen and (min-width: 960px) {
  :root {
    --main-bg-color: #181818;
  }
}

@media screen and (max-width: 960px) {
  :root {
    --main-bg-color: #fff;
  }
}
```

I'll stick with that despite this is not the expected behavior.
