### ISSUE TITLE
Cant make postcss works

### ISSUE THREAD

**Issue by equinusocio** [nuxt/nuxt.js#3960]
Hi, i can't make postcss working with Nuxt 2. I know that is supports postcss OOTB by adding the plugins, but it does do nothig.

I just added a `postcss.config.js` file (tried also with nuxt.config.js) to the project root:
```js
module.exports = {
  syntax: require('postcss-syntax'),
  plugins: {
    stylelint: {
      options: {
        configFile: './.stylelintrc'
      }
    },
    'postcss-easy-import': {
      extensions: '.pcss'
    },
    'postcss-preset-env': {
      stage: 0,
      autoprefixer: {
        grid: true
      },
      insertBefore: {
        'nesting-rules': require('postcss-mixins')()
      }
    },
    cssnano: { preset: 'advanced' },
    'postcss-reporter': { clearReportedMessages: true }
  }
}
```

Then my `vue` component looks like this:

```html
<template>
  <nav role="navigation">
    <a class="NagivationItem" href="#">
        LINK
        <sup>Soon</sup>
    </a>
  </nav>
</template>

<style scoped lang="postcss">
  .NagivationItem {
    color: var(--foregroundColor, #000);
    text-decoration: none;

    & sup {
      margin-left: 90px;
    }
  }
</style>
```

And nothig happens. The css output is:
```css
.NagivationItem {
  color: var(--foregroundColor, #000);
  text-decoration: none;

  & .c {
    margin-left: 90px;
  }
}

/* It should be .NavigationItem .c {} */
```
