### ISSUE TITLE
Travis gives fatal error when running "npm run generate" task

### ISSUE THREAD

**Issue by ahmetzeybek** [nuxt/nuxt.js#4684]
### Version

[v2.0.0](https://github.com/nuxt.js/releases/tag/v2.0.0)

### Steps to reproduce

```
> nuxt generate
[02:18:45] [FATAL] Nuxt Build Error
7
   ╭────────────────────────╮
   │                        │
   │   ✖ Nuxt Fatal Error   │
   │                        │
   │   Nuxt Build Error     │
   │                        │
   ╰────────────────────────╯
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8401">#c8401</a>)</em></sub></div>

**Comment by manniL** [comment]
Please get more into detail and try to provide a reproduction.

**Comment by zajca** [comment]
I run into same error with my site, but can't get more information since travis is ignoring my after_failure section:
Here is my travis build: https://travis-ci.com/zajca/zajca.cz/builds/96573392
and repository: https://github.com/zajca/zajca.cz

**Comment by manniL** [comment]
@zajca It's not Nuxt related then. Try to

* Reproduce the travis env locally (set `CI` env variable to true for example)
* Disable `build.quiet` so you have more detailed error messages on Travis.

**Comment by ahmetzeybek** [comment]
@zajca fixed with this configuration, I think it only gives error when os wasn't specified

```yaml
language: node_js
node_js:
  - 10

os:
  - osx

branches:
  only:
  - master

install:
  - yarn

script:
  - yarn run generate

deploy:
  provider: surge
  skip_cleanup: true
  project: ./dist/
  domain: jugendbotschafter.surge.sh
```
