### ISSUE TITLE
Nested custom media queries remain nested

### ISSUE THREAD

**Issue by smth** [nuxt/nuxt.js#5592]
### Version

[v2.6.2](https://github.com/nuxt.js/releases/tag/v2.6.2)

### Reproduction link

[https://codesandbox.io/embed/4lkmoxp30](https://codesandbox.io/embed/4lkmoxp30)

### Steps to reproduce

Enable postcss-custom-media

```js
postcss: {
  preset: {
    features: {
      'custom-media-queries': true
    }
  }
}
```

Define a custom media query

```css
@custom-media --for-tablet-portrait-up (min-width: 600px);
```

Nest a media query inside a CSS declaration

```css
.my-class {
  color: green;

  @media (--for-tablet-portrait-up) {
    color: red;
  }
}
```

### What is expected ?

postcss-custom-media usually handles nesting, outputting valid CSS

```css
.myclass {
  color: green;
}

@media (min-width: 600px) {
  .myclass {
    color: red;
  }
}
```

### What is actually happening?

Media query definitions are being translated, but nesting is not being resolved:

```css
.myclass {
  color: green;

  @media (min-width: 600px) {
    color: red;
  }
}
```

### Additional comments?

In the linked reproduction, I have added a nested media query to the `.green` class in `index.vue`.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9095">#c9095</a>)</em></sub></div>
