### ISSUE TITLE
`nuxt generate` doesn't include css '.svg-inline--fa' classes from FontAwesome

### ISSUE THREAD

**Issue by AAAC290992** [nuxt/nuxt.js#6565]
Following the docs, this is how I add icons within my NUXT project.

```javascript
// package.json

{
  ...
  "dependencies": {
    "@fortawesome/free-solid-svg-icons": "^5.1.0",
    "@nuxtjs/pwa": "^3.0.0-0",
    "nuxt": "^2.0.0",
    "nuxt-fontawesome": "^0.1.0",
    ...
  }
  ...
}
```
```javascript
// nuxt.config.js

{
  modules: [
    ...
    ['nuxt-fontawesome', {
      component: 'fa',
      imports: [
        {
          set: '@fortawesome/free-solid-svg-icons',
          icons: ['faSearch', ...]
        }
      ]
    }],
  ],
}
```
Here is the problem, I need to leave ``.svg-inline--fa { }`` even commented ``/* .svg-inline--fa { }  */`` so that Nuxt includes those classes in the generated static code. Otherwise, svg icons make a mess.
```html
<!-- ~/components/component.vue -->

<template>
  ...
    <fa icon="search" /> /* or */
    <fa :icon="faSearch" /> /* or */
    <fa :icon="['fas', 'search']" />
  ...
</template>

<style>
  .svg-inline--fa { } /* needed to include de following classes on generated static code */
</style>
```
I need this classes on generated static code to all svg icons work corretly. Those are classes from FontAwesome that **in _dev_ Nuxt does include**.
```css
svg:not(:root).svg-inline--fa {
    overflow: visible;
}
.svg-inline--fa.fa-w-16 {
    width: 1em;
}
.svg-inline--fa {
    display: inline-block;
    font-size: inherit;
    height: 1em;
    overflow: visible;
    vertical-align: -.125em;
}
```
