### ISSUE TITLE
PM2 config

### ISSUE THREAD

**Issue by miteyema** [nuxt/nuxt.js#7043]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://any.app.will.do](https://any.app.will.do)

### Steps to reproduce

When I run `pm2 start npm --name "nuxt" -- start`, no app is running on my Windows computer.
Please also see previous answers in https://github.com/nuxt/nuxt.js/issues/1541 or https://github.com/nuxt/nuxt.js/issues/67 

### What is expected ?

nuxt app should run on Windows using pm2

### What is actually happening?

nothing is running

![Screenshot 2020-03-02 at 12.30.59.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/94d517c0-5c25-11ea-81f3-ed7d77df5ac3.png)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10346">#c10346</a>)</em></sub></div>

**Comment by zacharytyhacz** [comment]
I'm not sure if windows would have it be any different, but when I need to run my nuxt project with pm2 is use this:

```bash
pm2 start npm -i 0 --name myproject --update-env --log-date-format 'DD-MM HH:mm:sds.SSS' -- run start
```

and my `package.json` looks like this:
```javascript
// this is default and untouched from inital nuxt project start
  "scripts": {
    "dev": "cross-env NODE_ENV=development nodemon server/index.js --watch server",
    "build": "nuxt build",
    "start": "cross-env NODE_ENV=production node server/index.js",
    "generate": "nuxt generate",
    "test": "jest"
  },
```

**Comment by robmellett** [comment]
Hey there,

This is how I run the apps on ubuntu, you might want to sanity check if it's a windows specific issue.

Here's a docker-compose file
```yml
version: '3'
services:
  web:
    image: robmellett/node:latest
    hostname: nuxt-app
    container_name: nuxt-app
    dns: 8.8.8.8
    volumes:
      - ./:/var/www/html
    tty: true
    ports:
      - 7000:80 # Web
      - 443:443 # HTTPS
```

Make sure your `ecosystem.config.js` looks like this
```js
module.exports = {
  apps: [
    {
      name: "nuxt-app",
      script: "npm",
      args: "start",
      port: 3000,
      instances: "max",
      exec_mode: "cluster",
      env: {
        NODE_ENV: "development"
      },
      env_production: {
        NODE_ENV: "production"
      }
    }
  ]
};
```

You can login to the docker host with `docker exec -it nuxt-app`

Then start the PM2 service with:
`pm2 start ecosystem.config.js --env production`
