### ISSUE TITLE
Docker compose can't bind the servers ip-address rather it's bind dockers inet address

### ISSUE THREAD

**Issue by Revel109** [nuxt/nuxt.js#7349]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://codesandbox.com](https://codesandbox.com)

### Steps to reproduce

how can you reproduce this here? You need docker-compose to do that.

### What is expected ?

It should run with machines inet address not dockers inet address. Hence I can't telnet it from another server.

### What is actually happening?

Already described. Need to fix it asap.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10643">#c10643</a>)</em></sub></div>

**Comment by TimvdEijnden** [comment]
@Revel109 could you share your `./docker-compose.yml` contents please?

**Comment by Revel109** [comment]
@TimvdEijnden 

```
version: "3"

services:
  nuxt:
    build: ./app/
    container_name: my_nuxt_app
    restart: always
    ports:
      - "3000:3000"
    command:
      "npm run start"
````
