### ISSUE TITLE
config webpackMiddleware to watch the code in docker

### ISSUE THREAD

**Issue by fingerpich** [nuxt/nuxt.js#8074]
I have used nuxtjs in docker in my mac
for development in mac we need to use polling to have it watched the code but i cant set it in nuxt.js
I have tested the following config which is recommended in this [link](https://dev.to/codemochi/hot-module-reloading-with-next-js-docker-development-environment-in-4-steps-32i8) and #2031
```
build: {
    devMiddleware: {
      watchOptions: {
        poll: 1000,
        aggregateTimeout: 300,
      }
    },
  }
```
but it doesn't work.

**Comment by Soviut** [comment]
@fingerpich If you've mounted your code as a volume, you should not need to use polling to watch, especially on OSX (on Windows it was necessary for a while). Watching should just work without any configuration.

Additionally, you can simply use `CHOKIDAR_USEPOLLING=1` environment variable to enable polling.

**Comment by fingerpich** [comment]
I have configured docker-compose as the following for ui, other services works and reload well.
```
  ui:
    container_name: ui
    restart: always
    build:
      context: ./ui
    ports:
      - "4005:4005"
    environment:
      - CHOKIDAR_USEPOLLING=1
      - NODE_ENV=development
    volumes:
      - ./ui/:/ui/
      - /ui/node_modules/
    command: yarn dev
```
dockerfile
```
FROM node:12-alpine
WORKDIR /ui

COPY package.json ./
COPY yarn.lock ./
RUN yarn
COPY . .
RUN yarn build
EXPOSE 4005
CMD [ "yarn", "dev" ]
```
but it doesn't reload on change.
