### ISSUE TITLE
got "FATAL  No build files found in /var/www/html/.nuxt/dist/server." on docker

### ISSUE THREAD

**Issue by handhikadj** [nuxt/nuxt.js#8239]
### Versions

- nuxt: 2.14.6
- node: LTS

### Reproduction

docker-compose.prod.yml: https://pastebin.com/hzutDRbi
node.prod.dockerfile: https://pastebin.com/XqahKHGH

got that error on production mode on docker
it runs flawlessly on development mode
<details open>
<summary>Additional Details</summary>

<br>

```
> my-app@1.0.0 start /var/www/html
> nuxt start


 FATAL  No build files found in /var/www/html/.nuxt/dist/server.
Use either `nuxt build` or `builder.build()` or start nuxt in development mode.

  Use either `nuxt build` or `builder.build()` or start nuxt in development mode.
  at VueRenderer._ready (node_modules/@nuxt/vue-renderer/dist/vue-renderer.js:4216:13)
  at async Server.ready (node_modules/@nuxt/server/dist/server.js:633:5)
  at async Nuxt._init (node_modules/@nuxt/core/dist/core.js:719:7)


   ╭─────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                     │
   │   ✖ Nuxt Fatal Error                                                                │
   │                                                                                     │
   │   Error: No build files found in /var/www/html/.nuxt/dist/server.                   │
   │   Use either `nuxt build` or `builder.build()` or start nuxt in development mode.   │
   │                                                                                     │
   ╰─────────────────────────────────────────────────────────────────────────────────────╯

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-app@1.0.0 start: `nuxt start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-app@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-22T13_41_06_556Z-debug.log

```
</details>

### Steps to reproduce
docker-compose.prod.yml: 
```
version: '3'

networks:
  nuxtproject:
    driver: bridge

services:
  webserver:
    build:
      context: .
      dockerfile: ./docker/nginx.dockerfile
    container_name: webserver
    ports:
      - "${FRONTEND_HOST}:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - nuxt
    networks:
      - nuxtproject

  nuxt:
    build:
      context: .
      dockerfile: ./docker/node.prod.dockerfile
    container_name: nuxt
    volumes:
      - .:/var/www/html
    ports:
      - "3000:3000"
    networks:
      - nuxtproject

  npm:
    image: node:lts-alpine
    container_name: npm
    volumes:
      - .:/var/www/html
    depends_on:
      - nuxt
    entrypoint: ['npm']
    networks:
      - nuxtproject

```

node.prod.dockerfile
```
FROM node:lts-alpine

WORKDIR /var/www/html

COPY package*.json /var/www/html/

COPY . /var/www/html/

RUN npm install && npm run build && \
    addgroup -g 2000 nodefrontend && \
    adduser -G nodefrontend -g nodefrontend -s /bin/sh -D nodefrontend && \
    chown nodefrontend:nodefrontend /var/www/html

ENV HOST 0.0.0.0

CMD ["npm", "start"]

```

### What is Expected?
the start up runs flawlessly on production mode

### What is actually happening?
failed at start up on production mode
