### ISSUE TITLE
Nuxt SSR  deployment on docker with pm2 has error.

### ISSUE THREAD

**Issue by farshidrezaei** [nuxt/nuxt.js#8704]
### Versions

- nuxt: v2.14.12
- node: v14.15.3

I did  run `nuxt build` command then,
when i run `pm2-runtime start ecosystem.yml` on docker, i get this error:

>  Error: No build files found in                                                   
>  /var/www/ui/ecosystem.config.yaml/.nuxt/dist/server.                             
>  Use either `nuxt build` or `builder.build()` or start nuxt in development mode.  

how i can solve that?

**Comment by farshidrezaei** [comment]
@Atinux 

ecosystem.yaml 

```yaml
apps:
      - name: App
        exec_mode: cluster
        instances: max
        script: ./node_modules/nuxt/bin/nuxt.js
        args: start
```
