### ISSUE TITLE
Removes quotes from font-family in production mode

### ISSUE THREAD

**Issue by ivodolenc** [nuxt/nuxt.js#9118]
**Issue**

Quotes are removed from `font-family` values in `production` mode (in CSS output).

Not sure, but I think it only happens when `extractCSS: true` is defined.

Current output:

```css
html {
  font-family: Inter, sans-serif;
}
```

Expected output:

```css
html {
  font-family: 'Inter', sans-serif;
}
```

I tried this solution, but it didn't solve the issue:

```js
// nuxt.config.js

export default {
  build: {
    postcss: {
      plugins: {
        cssnano: {
          preset: ['default', { minifyFontValues: { removeQuotes: false } }],
        },
      },
    },
  },
}
```

**Reproduction**

```js
// nuxt.config.js

export default {
  target: 'static',

  build: {
    extractCSS: true,
  },
}
```

- `create-nuxt-app`
- nuxt `v2.15.4`
- target `static`
- `yarn generate`
